aappnewsite/urls.py
import debug_toolbar

from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import DashboardView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('__debug__/', include(debug_toolbar.urls)),
    path('faicon/', include('faicon.urls')),

    path('', include("contact.urls")),
    path('', include("akaynt.urls")),
    path('koncurs/', include('konkurs.urls')),

    path('profile/', DashboardView.as_view(), name='dashboard'),
    path('profile/', include('calendarapp.urls')),
]

urlpatterns += i18n_patterns(
    path('sovet/', include('sovet.urls'), name='sovet'),
    path("", include("glavnaya.urls")),
    path("news/", include("news.urls")),
    path("", include("cust.urls")),
    path("smena/", include('smena.urls')),
    path("taski/", include('taski.urls')),

)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cust/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import *

urlpatterns = [
    #path('setting/', Setting),
    path('partner/', partner),
    path('', views.head),

    path('document/', document),
    path('faq/', faq),
    path('privacypolicy/', privacypolicy),
    path('contacts/', contact),
    path('aboutus/', aboutus),
    path('useragreement/', useragreement),

]

taski/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='listtaski'),
    path('create/', views.create),
    path('edit/<int:id>/', views.edit),
    path('delete/<int:id>/', views.delete),
    path('addtaski', views.addtaski, name='addtaski'),

]

taski/models.py
from news.models import *
from django.contrib.auth.models import User

from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField



class Zadacha(models.Model):

    STATUS_NEWS = (
        ('Publish', 'Опубликовать'),
        ('Not_to_publish', 'Не публиковать'),
    )

    status = models.CharField(default='Publish', max_length=30, choices=STATUS_NEWS, verbose_name='Статус')
    yved = models.BooleanField(default=False, verbose_name='Уведомить')
    title = models.CharField(max_length=255, db_index=True, verbose_name='Наименование')
    slug = models.SlugField(unique=True, verbose_name='Ссылка')
    content = RichTextUploadingField(blank=True, verbose_name='Описание')
    rubric = models.ForeignKey('news.Category', on_delete=models.CASCADE, verbose_name='Рубрика')
    image = models.ImageField(blank=True, upload_to='media/image/', null=True, verbose_name='Изображение')
    views = models.IntegerField(default=0, verbose_name='Количество просмотров')
    time = models.TimeField(default=0, verbose_name='Время просмотров')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    update_at = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post', kwargs={"slug": self.slug})

    class Meta:
        verbose_name = 'Задание(ю)'
        verbose_name_plural = 'Задания'
        ordering = ['-created_at']




class Vopros(models.Model):

    zadacha = models.ForeignKey(Zadacha, on_delete=models.CASCADE, related_name='voprosiki')
    author = models.ForeignKey(User, default='self', related_name='poster', on_delete=models.CASCADE)
    title = models.CharField(max_length=255, db_index=True, verbose_name='Наименование')
    content = RichTextUploadingField(blank=True, verbose_name='Описание')
    image = models.ImageField(blank=True, upload_to='media/image/', null=True, verbose_name='Изображение задачи')
    image_1 = models.ImageField(blank=True, upload_to='media/image/', null=True, verbose_name='Изображение')
    varian_1 = models.CharField(max_length=255, db_index=True, verbose_name='Ответ №1')
    otvet_1 = models.BooleanField(default=False, verbose_name='Верный')
    image_2 = models.ImageField(blank=True, upload_to='media/image/', null=True, verbose_name='Изображение')
    varian_2 = models.CharField(max_length=255, db_index=True, verbose_name='Ответ №2')
    otvet_2 = models.BooleanField(default=False, verbose_name='Верный')
    image_3 = models.ImageField(blank=True, upload_to='media/image/', null=True, verbose_name='Изображение')
    varian_3 = models.CharField(max_length=255, db_index=True, verbose_name='Ответ №3')
    otvet_3 = models.BooleanField(default=False, verbose_name='Верный')
    image_4 = models.ImageField(blank=True, upload_to='media/image/', null=True, verbose_name='Изображение')
    varian_4 = models.CharField(max_length=255, db_index=True, verbose_name='Ответ №4')
    otvet_4 = models.BooleanField(default=False, verbose_name='Верный')
    views = models.IntegerField(default=0, verbose_name='Количество пройденых')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    update_at = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Тест'
        verbose_name_plural = 'Тесты'
        ordering = ['-created_at']

taski/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget
from django.forms import ModelForm, TextInput, Textarea, Select, FileInput, SelectMultiple, CheckboxInput
from .models import *


class ReataskiForm(forms.ModelForm):
    class Meta:
        model = Zadacha
        fields = [ 'title_en', 'title_ru', 'slug', 'yved', 'content_ru', 'content_en', 'rubric', 'image', 'status']

        widgets = {
            "status": Select(attrs={'class': 'form-control', 'placeholder': 'Статус задачи'}),
            "yved": CheckboxInput(attrs={'class': 'form-control', 'placeholder': 'Уведомить'}),
            "title": TextInput(attrs={'class': 'form-control', 'placeholder': 'Название задачи'}),
            "title_ru": TextInput(attrs={'class': 'form-control', 'id': 'title_ru', 'placeholder': 'Название задачи [ru]'}),
            "title_en": TextInput(attrs={'class': 'form-control', 'placeholder': 'Название задачи [en]'}),
            "slug": TextInput(attrs={'class': 'form-control', 'id': 'slug', 'placeholder': 'ссылка'}),
            "content": forms.CharField(widget=CKEditorWidget()),
            "content_ru": forms.CharField(widget=CKEditorWidget()),
            "content_en": forms.CharField(widget=CKEditorWidget()),
            "rubric": Select(attrs={'class': 'form-control', 'placeholder': 'Категория задачи'}),
            "image": FileInput(attrs={'class': 'form-control', 'placeholder': 'Изображение задачи'}),
        }

class TaskiForm(forms.ModelForm):
    class Meta:
        model = Zadacha
        fields = [ 'title_en', 'title_ru', 'slug', 'yved', 'content_ru', 'content_en', 'rubric', 'image', 'status']

        widgets = {
            "status": Select(attrs={'class': 'form-control', 'placeholder': 'Статус задачи'}),
            "yved": CheckboxInput(attrs={'class': 'form-control', 'placeholder': 'Уведомить'}),
            "title": TextInput(attrs={'class': 'form-control', 'placeholder': 'Название задачи'}),
            "title_ru": TextInput(attrs={'class': 'form-control', 'id': 'title_ru', 'placeholder': 'Название задачи [ru]'}),
            "title_en": TextInput(attrs={'class': 'form-control', 'placeholder': 'Название задачи [en]'}),
            "slug": TextInput(attrs={'class': 'form-control', 'id': 'slug', 'placeholder': 'ссылка'}),
            "content": forms.CharField(widget=CKEditorWidget()),
            "content_ru": forms.CharField(widget=CKEditorWidget()),
            "content_en": forms.CharField(widget=CKEditorWidget()),
            "rubric": Select(attrs={'class': 'form-control', 'placeholder': 'Категория задачи'}),
            "image": FileInput(attrs={'class': 'form-control', 'placeholder': 'Изображение задачи'}),
        }

taski/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.http import HttpResponseNotFound
from .models import *
from .forms import *


# получение данных из бд
def index(request):
    zadacha = Zadacha.objects.all()
    return render(request, "taski/listtaski.html", {"zadacha": zadacha})


# сохранение данных в бд
def create(request):
    if request.method == "POST":
        zadacha = Zadacha()
        zadacha.title = request.POST.get("title")
        zadacha.age = request.POST.get("age")
        zadacha.save()
    return HttpResponseRedirect("/")


# изменение данных в бд
def edit(request, id):

    try:
        zadacha = Zadacha.objects.get(id=id)

        if request.method == "POST":
            zadacha.title = request.POST.get("title")
            zadacha.age = request.POST.get("age")
            zadacha.save()
            return HttpResponseRedirect("/")
        else:
            return render(request, "taski/redtaski.html", {"zadacha": zadacha})
    except Zadacha.DoesNotExist:
        return HttpResponseNotFound("<h2>Zadacha not found</h2>")



# удаление данных из бд
def delete(request, id):
    try:
        zadacha = Zadacha.objects.get(id=id)
        zadacha.delete()
        return HttpResponseRedirect("/")
    except Zadacha.DoesNotExist:
        return HttpResponseNotFound("<h2>Zadacha not found</h2>")


def addtaski(request):
    error = ''
    if request.method == 'POST':
        addtaski = TaskiForm(request.POST)
        if addtaski.is_valid():
            addtaski.save()
            slug = request.POST.get("slug")
            post = Post.objects.get(slug=slug)
            print(post)
            if post is None:
                print("none")
                return HttpResponseRedirect(request.path_info)
            else:
                error = 'Занято'
        else:
            error = 'Форма была не верна заполнена'

    addtaski = TaskiForm()

    data = {
        'addtaski': addtaski,
        'error' : error
    }

    return render(request, 'taski/addtaski.html', data)

templates/taski/addtaski.html
{% extends 'base-profile/base.html' %}
{% load static %}

{% block title %}Event Dashboard{% endblock title %}

{% block breadcrumb %}
    <div>
        <h1><i class="fa fa-dashboard"></i> Панель управления</h1>
        <p> Панель управления</p>
    </div>
    <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
        <li class="breadcrumb-item"><a href="#"> Панель управления</a></li>
    </ul>
{% endblock breadcrumb %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="tile row">
            <!--- Начало---->
                <p>Задания</p>
            <form method="post">
                {% csrf_token %}
                {{ addtaski.media }}


                {{ addtaski.status }}<br>
                Уведомить{{ addtaski.yved }}<br>
                <nav>
                    <div class="nav nav-tabs" id="nav-tab" role="tablist">
                        <button class="nav-link active" id="title-ru-tab" data-bs-toggle="tab" data-bs-target="#title-ru" type="button" role="tab" aria-controls="nav-home" aria-selected="true">Название [ru]</button>
                        <button class="nav-link" id="title-en-tab" data-bs-toggle="tab" data-bs-target="#title-en" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">Название [en]</button>
                    </div>
                </nav>
                <div class="tab-content" id="nav-tabContent">
                    <div class="tab-pane fade show active" id="title-ru" role="tabpanel" aria-labelledby="title-ru-tab">{{ addtaski.title_ru }}</div>
                    <div class="tab-pane fade" id="title-en" role="tabpanel" aria-labelledby="title-en-tab">{{ addtaski.title_en }}</div>
                </div>
                <br>
            {{ addtaski.slug }}<br>
                <nav>
                    <div class="nav nav-tabs" id="nav-content" role="tablist">
                        <button class="nav-link active" id="content-ru-tab" data-bs-toggle="tab" data-bs-target="#content-ru" type="button" role="tab" aria-controls="nav-home" aria-selected="true">Описание [ru]</button>
                        <button class="nav-link" id="content-en-tab" data-bs-toggle="tab" data-bs-target="#content-en" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">Описание [en]</button>
                    </div>
                </nav>
                <div class="tab-content" id="nav-tab-content">
                    <div class="tab-pane fade show active" id="content-ru" role="tabpanel" aria-labelledby="content-ru-tab">{{ addtaski.content_ru }}</div>
                    <div class="tab-pane fade" id="content-en" role="tabpanel" aria-labelledby="content-en-tab">{{ addtaski.content_en }}</div>
                </div>
                <br>
                {{ addtaski.category }}<br>
                {{ addtaski.image }}<br>
                <br>
                <button class="btn btn-success" type="submit">Добавить</button>
            </form>





            <!--- Конец---->
        </div>
    </div>
</div>

{% endblock content %}

{% block extrascripts %}
    <script type="text/javascript" src="{% static 'style-profile/js/plugins/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'style-profile/js/plugins/dataTables.bootstrap.min.js' %}"></script>
    <script type="text/javascript">$('#sampleTable').DataTable();</script>
<script>
    $(document).ready(function(){
    function rus_to_latin ( str ) {

    var ru = {
        'а': 'a', 'б': 'b', 'в': 'v', 'г': 'g', 'д': 'd',
        'е': 'e', 'ё': 'e', 'ж': 'j', 'з': 'z', 'и': 'i',
        'к': 'k', 'л': 'l', 'м': 'm', 'н': 'n', 'о': 'o',
        'п': 'p', 'р': 'r', 'с': 's', 'т': 't', 'у': 'u',
        'ф': 'f', 'х': 'h', 'ц': 'c', 'ч': 'ch', 'ш': 'sh',
        'щ': 'shch', 'ы': 'y', 'э': 'e', 'ю': 'u', 'я': 'ya', ' ': '_',
    }, n_str = [];

    str = str.replace(/[ъь]+/g, '').replace(/й/g, 'i');

    for ( var i = 0; i < str.length; ++i ) {
       n_str.push(
              ru[ str[i] ]
           || ru[ str[i].toLowerCase() ] == undefined && str[i]
           || ru[ str[i].toLowerCase() ].toUpperCase()
       );
    }

    return n_str.join('');
}

        $('#title_ru').keyup(function(){
            var Value = $('#title_ru').val();
            $('#slug').empty();
            $('#slug').val(rus_to_latin(Value));
        });
        })
    </script>
{% endblock extrascripts %}

templates/taski/listtaski.html
{% extends 'base-profile/base.html' %}
{% load static %}

{% block title %}Event Dashboard{% endblock title %}

{% block breadcrumb %}
    <div>
        <h1><i class="fa fa-dashboard"></i> Панель управления</h1>
        <p> Панель управления</p>
    </div>
    <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
        <li class="breadcrumb-item"><a href="#"> Панель управления</a></li>
    </ul>
{% endblock breadcrumb %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="tile row">
            <!--- Начало---->
 <div class="col-md-11"><h2>Список</h2></div>
             <div class="col-md-1">
                 <a class="btn btn-success" href="{% url 'addtaski' %}" role="button">Добавить</a>
             </div>

    {% if zadacha.count > 0 %}
    <div class="col-md-12">
    <table>
        <thead><th>Id</th><th>название</th><th></th></thead>
        {% for zadacha in zadacha %}
        <tr>
            <td>{{ zadacha.id }}</td>
            <td>{{ zadacha.title }}</td>
            <td><a href="edit/{{zadacha.id}}">Изменить</a> | <a href="delete/{{zadacha.id}}">Удалить</a></td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
        </div>
            <!--- Конец---->
        </div>
    </div>
</div>

{% endblock content %}

{% block extrascripts %}
    <script type="text/javascript" src="{% static 'style-profile/js/plugins/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'style-profile/js/plugins/dataTables.bootstrap.min.js' %}"></script>
    <script type="text/javascript">$('#sampleTable').DataTable();</script>
{% endblock extrascripts %}

templates/taski/redtaski.html
{% extends 'base-profile/base.html' %}
{% load static %}

{% block title %}Event Dashboard{% endblock title %}

{% block breadcrumb %}
    <div>
        <h1><i class="fa fa-dashboard"></i> Панель управления</h1>
        <p> Панель управления</p>
    </div>
    <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
        <li class="breadcrumb-item"><a href="#"> Панель управления</a></li>
    </ul>
{% endblock breadcrumb %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="tile row">
            <!--- Начало---->
                <form method="POST">
        {% csrf_token %}
        {{zadacha.title_ru}}<br>
                    <input type="text" name="name" value="{{zadacha.title_ru}}" />
                   {{ zadacha.media }}

<select name="status" class="form-control" placeholder="Статус задачи" id="id_status">
    {{ zadacha.status }}
</select>
                {{ zadacha.status }}<br>
                Уведомить{{ zadacha.yved }}<br>
                <nav>
                    <div class="nav nav-tabs" id="nav-tab" role="tablist">
                        <button class="nav-link active" id="title-ru-tab" data-bs-toggle="tab" data-bs-target="#title-ru" type="button" role="tab" aria-controls="nav-home" aria-selected="true">Название [ru]</button>
                        <button class="nav-link" id="title-en-tab" data-bs-toggle="tab" data-bs-target="#title-en" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">Название [en]</button>
                    </div>
                </nav>
                <div class="tab-content" id="nav-tabContent">
                    <div class="tab-pane fade show active" id="title-ru" role="tabpanel" aria-labelledby="title-ru-tab">{{ zadacha.title_ru }}</div>
                    <div class="tab-pane fade" id="title-en" role="tabpanel" aria-labelledby="title-en-tab">{{ zadacha.title_en }}</div>
                </div>
                <br>
            {{ zadacha.slug }}<br>
                <nav>
                    <div class="nav nav-tabs" id="nav-content" role="tablist">
                        <button class="nav-link active" id="content-ru-tab" data-bs-toggle="tab" data-bs-target="#content-ru" type="button" role="tab" aria-controls="nav-home" aria-selected="true">Описание [ru]</button>
                        <button class="nav-link" id="content-en-tab" data-bs-toggle="tab" data-bs-target="#content-en" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">Описание [en]</button>
                    </div>
                </nav>
                <div class="tab-content" id="nav-tab-content">
                    <div class="tab-pane fade show active" id="content-ru" role="tabpanel" aria-labelledby="content-ru-tab">{{ zadacha.content_ru }}</div>
                    <div class="tab-pane fade" id="content-en" role="tabpanel" aria-labelledby="content-en-tab">{{ zadacha.content_en }}</div>
                </div>
                <br>
                {{ zadacha.category }}<br>
                {{ zadacha.image }}<br>
                <br>
        <input type="submit" value="Сохранить" >
    </form>
            <!--- Конец---->
        </div>
    </div>
</div>

{% endblock content %}

{% block extrascripts %}
    <script type="text/javascript" src="{% static 'style-profile/js/plugins/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'style-profile/js/plugins/dataTables.bootstrap.min.js' %}"></script>
    <script type="text/javascript">$('#sampleTable').DataTable();</script>
{% endblock extrascripts %}

templates/taski/taski.html
{% extends 'base-profile/base.html' %}
{% load static %}

{% block title %}Event Dashboard{% endblock title %}

{% block breadcrumb %}
    <div>
        <h1><i class="fa fa-dashboard"></i> Панель управления</h1>
        <p> Панель управления</p>
    </div>
    <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
        <li class="breadcrumb-item"><a href="#"> Панель управления</a></li>
    </ul>
{% endblock breadcrumb %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="tile row">
            <!--- Начало---->

            <!--- Конец---->
        </div>
    </div>
</div>

{% endblock content %}

{% block extrascripts %}
    <script type="text/javascript" src="{% static 'style-profile/js/plugins/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'style-profile/js/plugins/dataTables.bootstrap.min.js' %}"></script>
    <script type="text/javascript">$('#sampleTable').DataTable();</script>
{% endblock extrascripts %}