aappnewsite/urls.py
import debug_toolbar

from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import DashboardView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('__debug__/', include(debug_toolbar.urls)),
    path('faicon/', include('faicon.urls')),

    path('', include("contact.urls")),
    path('', include("akaynt.urls")),
    path('koncurs/', include('konkurs.urls')),

    path('profile/', DashboardView.as_view(), name='dashboard'),
    path('profile/', include('calendarapp.urls')),
]

urlpatterns += i18n_patterns(
    path('sovet/', include('sovet.urls'), name='sovet'),
    path("", include("glavnaya.urls")),
    path("news/", include("news.urls")),
    path("", include("cust.urls")),
    path("smena/", include('smena.urls')),
    path("taski/", include('taski.urls')),

)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cust/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import *

urlpatterns = [
    #path('setting/', Setting),
    path('partner/', partner),
    path('', views.head),

    path('document/', document),
    path('faq/', faq),
    path('privacypolicy/', privacypolicy),
    path('contacts/', contact),
    path('aboutus/', aboutus),
    path('useragreement/', useragreement),

]

news/urls.py
from django.urls import path
from . import views
from .views import *

urlpatterns = [
    path('', Home.as_view(), name='glavnaya'),
    path('category/<str:slug>/', PostsByCategory.as_view(), name='category'),
    path('tag/<str:slug>/', PostsByTag.as_view(), name='tag'),
    path('news/<str:slug>/', GetPost.as_view(), name='post'),
    path('post-comments/', base_view),
    path('create-comments/', create_comment, name='comment_create'),
    path('comment-complain/', complain, name='comment_complain'),
    path('create-child-comment/', create_child_comment, name='comment_child_create'),

    path('listnews', views.listnews, name='listnews'),



    path('addnews', views.addnews, name='addnews'),
    path('addnewscategory', views.addnewscategory, name='addnewscategory'),
    path('addnewstag', views.addnewstag, name='addnewstag'),

]


news/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey
from django.contrib.auth.models import User

from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericRelation


class Category(MPTTModel):
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children',
                            verbose_name='Родитель')
    name = models.CharField(max_length=255, verbose_name='Имя рубрики')
    slug = models.SlugField(max_length=255, unique=True, verbose_name='Ссылка')
    photo = models.ImageField(blank=True, upload_to='image', null=True, verbose_name='Изображение')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category', kwargs={"slug": self.slug})

    class MPTTMeta:
        order_insertion_by = ['name']

    class Meta:
        verbose_name = 'Рубрика'
        verbose_name_plural = 'Рубрики'


class Tag(models.Model):
    BUTTON = (
        ('Publish', 'Опубликовать'),
        ('Not_to_publish', 'Не публиковать'),
    )

    button = models.CharField(max_length=30, choices=BUTTON, verbose_name='Статус')
    name = models.CharField(max_length=30, verbose_name='Название(ru)')
    image = models.ImageField(blank=True, null=True, verbose_name='Изображение')
    slug = models.SlugField(max_length=255, unique=True, verbose_name='Ссылка')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('tag', kwargs={"slug": self.slug})

    class Meta:
        verbose_name = 'Метка'
        verbose_name_plural = 'Метки'
        ordering = ['name']


class Post(models.Model):
    author = models.ForeignKey(User, default='self',  related_name='news_author', verbose_name='Автор', on_delete=models.CASCADE)

    STATUS_NEWS = (
        ('Publish', 'Опубликовать'),
        ('Not_to_publish', 'Не публиковать'),
    )

    status = models.CharField(default='P', max_length=30, choices=STATUS_NEWS, verbose_name='Статус')
    yved = models.BooleanField(default=False, verbose_name='Уведомить')
    title = models.CharField(max_length=255, db_index=True, verbose_name='Наименование')
    slug = models.SlugField(unique=True, verbose_name='Ссылка')
    content = RichTextUploadingField(blank=True, verbose_name='Описание')
    category = TreeForeignKey('Category', verbose_name='Рубрики', on_delete=models.CASCADE, null=True, blank=True,
                              db_index=True)
    tags = models.ManyToManyField(Tag, verbose_name='Тэг')
    image = models.ImageField(blank=True, upload_to='media/image/', null=True, verbose_name='Изображение')
    views = models.IntegerField(default=0, verbose_name='Количество просмотров')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    update_at = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post', kwargs={"slug": self.slug})

    class Meta:
        db_table = "news_post"
        verbose_name = 'Статья(ю)'
        verbose_name_plural = 'Статьи'
        ordering = ['-created_at']


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='автор', on_delete=models.CASCADE)
    text = models.TextField(verbose_name='текст коментария')
    parent = models.ForeignKey('self', verbose_name='Коментарий к коментарию', blank=True, null=True,
                               related_name='comment_children', on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=True, verbose_name='Дата создания комментария')
    is_child = models.BooleanField(default=False)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Пост')

    def __str__(self):
        return str(self.id)

    @property
    def get_parent(self):
        if not self.parent:
            return ""
        return self.parent


    class Meta:
        verbose_name = 'Коментарии'
        verbose_name_plural = 'Коментарии'


class Complain(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='автор', on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Запись')
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, verbose_name='Коментарий')
    text = models.TextField()

    class Meta:
        verbose_name = 'Жалобы'
        verbose_name_plural = 'Жалобы'

news/views.py
from django.shortcuts import render, redirect
from django.db import transaction
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.views.generic import ListView, DetailView
from .models import Post, Category, Tag, Comment, Complain
from django.db.models import F
from django.template.defaulttags import register
from .utils import create_comments_tree
from .forms import CommentForm, PostForm, TagForm, CategoryForm


@register.filter
def get_all_tag(value):
    return Tag.objects.all()

@register.filter
def get_all_category(value):
    return Category.objects.all()

def get_rubrics_tag(self, context):
    if self.request.LANGUAGE_CODE == "ru":
        context['title_rubrics'] = 'Все рубрики'
    if self.request.LANGUAGE_CODE == "en":
        context['title_rubrics'] = 'All rubrics'

    if self.request.LANGUAGE_CODE == "ru":
        context['title_tag'] = 'Все теги'
    if self.request.LANGUAGE_CODE == "en":
        context['title_tag'] = 'All tag'

class Home(ListView):
    model = Post
    template_name = 'news/news.html'
    context_object_name = 'posts'
    paginate_by = 2

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        get_rubrics_tag(self, context)

        return context

class PostsByCategory(ListView):
    template_name = 'news/news.html'
    context_object_name = 'posts'
    paginate_by = 4
    allow_empty = False

    def get_queryset(self):
        return Post.objects.filter(category__slug=self.kwargs['slug'])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.LANGUAGE_CODE == "ru":
            buffer = Category.objects.get(slug=self.kwargs['slug'])
            context['title'] = "Категория " + buffer.name_ru
        if self.request.LANGUAGE_CODE == "en":
            buffer = Category.objects.get(slug=self.kwargs['slug'])
            context['title'] = "Category " + buffer.name_en

        return context

class PostsByTag(ListView):
    template_name = 'news/news.html'
    context_object_name = 'posts'
    paginate_by = 4
    allow_empty = False

    def get_queryset(self):
        return Post.objects.filter(tags__slug=self.kwargs['slug'])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        buffer = Tag.objects.get(slug=self.kwargs['slug'])
        get_rubrics_tag(self, context)
        if self.request.LANGUAGE_CODE == "ru":
            context['title'] = 'Записи по тегу ' + str(buffer.name_ru)
        if self.request.LANGUAGE_CODE == "en":
            context['title'] = 'Entries by tag ' + str(buffer.name_en)

        return context

class GetPost(DetailView):
    model = Post
    template_name = 'news/newsdetails.html'
    context_object_name = 'post'
    def get_context_data(self, **kwargs):
        context = super(GetPost, self).get_context_data(**kwargs) #Достаем контекст из urls
        slug = self.kwargs.get(self.slug_url_kwarg, None) #Достаём slug из контекста
        comment_form = CommentForm(self.request.POST or None)
        coment = Comment.objects.filter(post__slug=slug) # Извлекаем нужные коментарии
        context['comm'] = create_comments_tree(coment)
        context['form'] = comment_form
        return context # Возвращаем контекст

def base_view(request):
    comments = Comment.objects.all()
    result = create_comments_tree(comments)
    comment_form = CommentForm(request.POST or None)
    return render(request, 'news/newsdetails.html', {'comments': result, 'comment_form': comment_form})

def create_comment(request):
    print(request)
    if request.method == "POST":
        user_name = request.POST.get('user')
        new_comment = Comment()
        new_comment.user = User.objects.get(username=user_name)
        new_comment.text = request.POST.get("text")
        new_comment.object_id = 1
        new_comment.parent = None
        new_comment.is_child = False
        new_comment.post = Post.objects.get(slug=request.POST.get("slug"))
        new_comment.save()
    return redirect(request.META.get('HTTP_REFERER','redirect_if_referer_not_found'))

@transaction.atomic
def complain(request):
    if request.method == "POST":
        user_name = request.POST.get('user')
        comp = Complain()
        comp.user = User.objects.get(username=user_name)
        comp.post = Post.objects.get(slug=request.POST.get("slug"))
        comp.comment = Comment.objects.get(id=request.POST.get("com_id"))
        comp.text = request.POST.get("text")
        comp.save()
        comments_ = Comment.objects.filter(post__slug=request.POST.get("slug"))
        comments_list = create_comments_tree(comments_)
    return render(request, 'news/newsdetails.html', {'comments': comments_list})

@transaction.atomic
def create_child_comment(request):
    user_name = request.POST.get('user')
    current_id = request.POST.get('id')
    slug = request.POST.get('slug')
    text = request.POST.get('text')
    user = User.objects.get(username=user_name)
    post = Post.objects.get(slug=slug)
    print(post)
    parent = Comment.objects.get(id=int(current_id))
    is_child = False if not parent else True
    Comment.objects.create(
        user=user, text=text, post=post,
        parent=parent, is_child=is_child
    )
    comments_ = Comment.objects.filter(post__slug=slug)
    comments_list = create_comments_tree(comments_)
    return render(request, 'news/newsdetails.html', {'comments': comments_list})

#-------------ВЫВОД-----------

def listnews(request):

    listnews = Post()

    data = {
        'listnews': listnews
    }

    return render(request, 'news/list/list_news.html', data)

#-------------РЕДАКТИРОВАНИЕ-----------


#-------------ДОБАВЛЕНИЕ-----------

def addnews(request):
    error = ''
    if request.method == 'POST':
        newspost = PostForm(request.POST)
        if newspost.is_valid():
            newspost.save()
            slug = request.POST.get("slug")
            post = Post.objects.get(slug=slug)
            print(post)
            if post is None:
                print("none")
                return HttpResponseRedirect(request.path_info)
            else:
                error = 'Занято'
        else:
            error = 'Форма была не верна заполнена'

    newspost = PostForm()

    data = {
        'newspost': newspost,
        'error' : error
    }

    return render(request, 'news/add/add_news.html', data)

def addnewstag(request):
    error = ''
    if request.method == 'POST':
        newstags = TagForm(request.POST)
        if newstags.is_valid():
            newstags.save()
            slug = request.POST.get("slug")
            tag = Tag.objects.get(slug=slug)
            print(tag)
            if tag is None:
                print("none")
                return HttpResponseRedirect(request.path_info)
            else:
                error = 'Занято'
        else:
            error = 'Форма была не верна заполнена'

    newstags = TagForm()

    data = {
        'newstags': newstags,
        'error' : error
    }

    return render(request, 'news/add/add_news_tags.html', data)

def addnewscategory(request):
    error = ''
    if request.method == 'POST':
        newscategory = CategoryForm(request.POST)
        if newscategory.is_valid():
            newscategory.save()
            slug = request.POST.get("slug")
            category = Category.objects.get(slug=slug)
            print(category)
            if category is None:
                print("none")
                return HttpResponseRedirect(request.path_info)
            else:
                error = 'Занято'
        else:
            error = 'Форма была не верна заполнена'

    newscategory = CategoryForm()

    data = {
        'newscategory': newscategory,
        'error' : error
    }

    return render(request, 'news/add/add_news_category.html', data)

templates/news/comments.html
{% extends 'base-site/base.html' %}
{% load static%}

{% load comments_tree %}
{% load crispy_forms_tags %}

{% block body %}

<div class="row">

    <div class="col-md-3">

    </div>
    <div class="col-md-6">
        {{ comments|comments_filter }}
        <hr>
        <div class="col-md-12">
            <form action="{% url 'comment_create' %}" method="POST">
                {% csrf_token %}
                {{ comment_form|crispy }}
                <input type="submit" class="btn btn-ptimary" value="Отправить">
            </form>
        </div>
    </div>
    <div class="col-md-3">

    </div>

</div>

{% endblock %}

templates/news/news.html
{% extends 'base-site/base.html' %}
{% load static%}
{% load mptt_tags %}


{% block body %}
        <!--================Boot Area =================-->
<p>12165465</p>

        <!--================Categories Banner Area =================-->

<section id="ts-hero" class="ts-separate-bg-element">



<!--================Categories Product Area =================-->
<main id="ts-main">
        <section class="categories_product_main p_80">
            <div class="container">
                <div class="categories_main_inner">
                    <div class="row row_disable">
                        <div class="col-lg-3 float-md-left">
                             <!--- Категории --->
                            <section class="solid_banner_area">
                                <div class="container">
                                    <div class="solid_banner_inner">
                                        <h3>{{ title_rubrics }}</h3>
                                            <ul>
                                                {% for a in 1|get_all_category %}
                                                    <li><a href="{{ a.get_absolute_url }}">{{ a.name }}</a></li>
                                                {% endfor %}
                                            </ul>
                                    </div>

                                    <div class="solid_banner_inner">
                                        <h3>{{ title_tag }}</h3>
                                            <ul>
                                                {% for a in 1|get_all_tag %}
                                                    <li><a href="{{ a.get_absolute_url }}">{{ a.name }}</a></li>
                                                {% endfor %}
                                            </ul>
                                    </div>

                                </div>
                            </section>
                            <!--- Новости --->
                        </div>
                        <div class="col-lg-9 float-md-right">
                             <h3>{{ title }}</h3>
							<div class="c_product_grid_details">
                                {% for post in posts %}
                                <div class="c_product_item">
                                    <div class="row">
                                            <div class="c_product_text">
                                                <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                                                        {{ post.content|truncatewords_html:20|safe }}
                                                <h6><a href="{{ post.get_absolute_url }}"><span>Далее</span></a></h6>
                                                        <br><br>
                                                <div class="blog-info float-left">
                                                    <span class="author-name">
                                                        <i class="fa fa-angle-right"></i>
                                                        <a href="{{ post.category.get_absolute_url }}"> {{ post.category }}</a>
                                                    </span>
                                                    <span class="categories">
                                                        <i class="fa fa-tag"></i>
                                                        {% if post.tags.exists %}
                                                            {% for tag in post.tags.all %}
                                                            <a href="{{ tag.get_absolute_url }}">{{ tag.name }}</a>
                                                            {% endfor %}
                                                        {% endif %}

                                                    </span>
                                                    <span class="comments-number">
                                                        <i class="fa fa-comment"></i>
                                                        <a href="#">0 Comment</a>
                                                    </span>
                                                </div>
                                                    <div class="float-right"> <h6> Дата: <span> {{ post.created_at|date:"j F Y" }}</span></h6> </div>
                                            </div>

                                    </div>
                                </div>
                                 {% endfor %}
		<!--================Paginations Product Area =================-->
                                {% if page_obj.has_other_pages %}

                                <nav aria-label="Page navigation example" class="pagination_area">
                                  <ul class="pagination">

                                      {% for p in page_obj.paginator.page_range %}
                                        {% if page_obj.number == p %}
                                            <li class="page-item"><a class="page-link" href="?page={{ p }}">{{ p }}</a></li>
                                        {% elif p > page_obj.number|add:-3 and p < page_obj.number|add:3 %}
                                            <li class="page-item"><a class="page-link" href="?page={{ p }}">{{ p }}</a></li>
                                        {% endif %}
                                      {% endfor %}

                                      {% if page_obj.has_next %}
                                        <li class="page-item next"><a class="page-link" href="?page={{ page_obj.next_page_number }}"><i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
                                      {% endif %}
                                  </ul>
                                </nav>
                                {% endif %}
		<!--================Paginations Product Area =================-->
                            </div>
                        </div>
                        <div class="col-lg-3 float-md-right">
                            <div class="categories_sidebar">
                                <aside class="l_widgest l_p_categories_widget">






                                </aside>


                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!--================End Categories Product Area =================-->
</main>

</section>
        {% endblock %}


templates/news/newsdetails.html
{% extends 'base-site/base.html' %}
{% load static%}
{% load static i18n %}
{% load comments_tree %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" href="{% static 'img/fav-icon.png'%}" type="image/x-icon" />
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Persuit</title>
        <!-- Icon css link -->
        <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
        <link href="{% static 'vendors/line-icon/css/simple-line-icons.css' %}" rel="stylesheet">
        <link href="{% static 'vendors/elegant-icon/style.css' %}" rel="stylesheet">
        <!-- Bootstrap -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <!-- Rev slider css -->
        <link href="{% static 'vendors/revolution/css/settings.css' %}" rel="stylesheet">
        <link href="{% static 'vendors/revolution/css/layers.css' %}" rel="stylesheet">
        <link href="{% static 'vendors/revolution/css/navigation.css' %}" rel="stylesheet">
        <!-- Extra plugin css -->
        <link href="{% static 'vendors/owl-carousel/owl.carousel.min.css' %}" rel="stylesheet">
        <link href="{% static 'vendors/bootstrap-selector/css/bootstrap-select.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
        <link href="{% static 'css/responsive.css' %}" rel="stylesheet">
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <!--================Top Header Area =================-->
        <!--================Boot Area =================-->

        {% block body %}
        <!--================Categories Banner Area =================-->
        <section class="solid_banner_area">
                                <div class="container">
                                    <div class="solid_banner_inner">
                                        <h3>{{ title_rubrics }}</h3>
                                            <ul>
                                                {% for a in 1|get_all_category %}
                                                    <li><a href="{{ a.get_absolute_url }}">{{ a.name }}</a></li>
                                                {% endfor %}
                                            </ul>
                                    </div>

                                    <div class="solid_banner_inner">
                                        <h3>{{ title_tag }}</h3>
                                            <ul>
                                                {% for a in 1|get_all_tag %}
                                                    <li><a href="{{ a.get_absolute_url }}">{{ a.name }}</a></li>
                                                {% endfor %}
                                            </ul>
                                    </div>

                            </section>
        <!--================End Categories Banner Area =================-->



<!--================Categories Product Area =================-->
        <section class="categories_product_main p_80">
            <div class="container">
                <div class="categories_main_inner">
                    <div class="row row_disable">
                        <div class="col-lg-12">

							<div class="c_product_grid_details">

                                <div class="c_product_item">
                                    <div class="row">
                                            <div class="c_product_text">
                                                <h5 id="ddd">{{ postnews.slug }}</h5>
                                                 <h3>{{ post.title }}</h3>
                                                        {{ post.content|safe }}


                                            </div>

                                    </div>
                                    <hr>
                                    <ul>
                                    {{ comm|comments_filter}}
                                    </ul>
                                        <form action="{% url 'comment_create' %}" method="POST">
                {% csrf_token %}
                <textarea name="text" cols="40" rows="10" class="textarea" required="" id="id_text"></textarea>
                <input type="button" class="btn btn-ptimary" value="Отправить" id="bt">
            </form>

                                </div>



                                    <span class="categories">
                                        <i class="fa fa-tag"></i>
                                        {% if post.tags.exists %}
                                                            {% for tag in post.tags.all %}
                                                            <a href="{{ tag.get_absolute_url }}">{{ tag.name }}</a>
                                                            {% endfor %}
                                                        {% endif %}

                                    </span>
                                    <div class="float-right"> <h6>{% trans 'Дата:' %} <span> {{ post.created_at|date:"Y-m-d" }}</span></h6> </div>

                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--================End Categories Product Area =================-->
        {% endblock %}

        <!--================Footer Area =================-->
    </body>
</html>

</body>
</html>